name: find_pr
description: Finds PR details for an workflow_run event. Works for push, pull_request, and issue_comment events that trigger a workflow_run.

inputs:
  github_token:
    description: "Your github token."
    required: true
outputs:
  pr_number:
    description: "Pull request number."
  source_repo:
    description: "Source repo."
  source_branch:
    description: "Source branch."
  found_pr:
    description: "Found PR."
  sha:
    description: "SHA."
  mergeable:
    description: "Mergeable."
  merge_sha:
    description: "Merge SHA."
  labels:
    description: "Labels."

runs:
  using: "node20"
  main: "dist/index.js"
